"""add Genre model

Revision ID: 3607a46d9185
Revises: dfb74e4d178f
Create Date: 2022-05-22 14:18:13.095496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3607a46d9185'
down_revision = 'dfb74e4d178f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###
